// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOcgzJbRFOi94-3fl6zkbDAaVql2qdl_o',
    appId: '1:1005044261387:web:1b31005363ec6b5fd0dd0e',
    messagingSenderId: '1005044261387',
    projectId: 'smart-po-7583a',
    authDomain: 'smart-po-7583a.firebaseapp.com',
    storageBucket: 'smart-po-7583a.appspot.com',
    measurementId: 'G-8Y4TB863D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV0fOgHRr9AJS_Rk8HDBhDStTsYlsg-f8',
    appId: '1:1005044261387:android:dcfec4a117ed79a1d0dd0e',
    messagingSenderId: '1005044261387',
    projectId: 'smart-po-7583a',
    storageBucket: 'smart-po-7583a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs0kiY4geaLlP4k89MksJbNHDoQfmTpCk',
    appId: '1:1005044261387:ios:cf6780d28ee16112d0dd0e',
    messagingSenderId: '1005044261387',
    projectId: 'smart-po-7583a',
    storageBucket: 'smart-po-7583a.appspot.com',
    iosBundleId: 'com.orthocareinnovations.smartpo',
  );
}
